ALTER TABLE jobs ADD COLUMN stage TEXT;
ALTER TABLE jobs ADD COLUMN processed INTEGER DEFAULT 0;
ALTER TABLE jobs ADD COLUMN total INTEGER;
ALTER TABLE jobs ADD COLUMN progress_detail_json TEXT;
ALTER TABLE jobs ADD COLUMN heartbeat_at TEXT;
